//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public System.Guid ExternalID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SerializedUserInfo { get; set; }
    }
}
